jobs/startup: populate db with test data in DEV mode
when Application starts for the first time to help development.

Both Fixtures class (the Siena one and the Play! Framework) should
be patched, as the model prefix is hardwired.

And forget about the in memory H2 database + Siena combination!
Something is off with String fields. See below!

@85ijeaek4
Internal Server Error (500) for request GET /client?view=Active

Execution exception (In /app/com/openseedbox/models/Torrent.java around line 41)
SienaException occurred : java.lang.IllegalArgumentException: Can not set java.lang.String field com.openseedbox.models.Torrent.name to org.h2.jdbc.JdbcClob

play.exceptions.JavaExecutionException: java.lang.IllegalArgumentException: Can not set java.lang.String field com.openseedbox.models.Torrent.name to org.h2.jdbc.JdbcClob
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:485)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:467)
	at play.mvc.ActionInvoker.invokeControllerCatchMethods(ActionInvoker.java:231)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:168)
	at Invocation.HTTP Request(Play!)
Caused by: siena.SienaException: java.lang.IllegalArgumentException: Can not set java.lang.String field com.openseedbox.models.Torrent.name to org.h2.jdbc.JdbcClob
	at siena.Util.setField(Util.java:286)
	at siena.jdbc.JdbcMappingUtils.setFromObject(JdbcMappingUtils.java:205)
	at siena.jdbc.JdbcMappingUtils.mapField(JdbcMappingUtils.java:186)
	at siena.jdbc.JdbcMappingUtils.mapObject(JdbcMappingUtils.java:79)
	at siena.jdbc.JdbcMappingUtils.mapObject(JdbcMappingUtils.java:67)
	at siena.jdbc.JdbcMappingUtils.mapList(JdbcMappingUtils.java:92)
	at siena.jdbc.JdbcPersistenceManager.doFetch(JdbcPersistenceManager.java:636)
	at siena.jdbc.JdbcPersistenceManager.fetch(JdbcPersistenceManager.java:728)
	at siena.jdbc.H2PersistenceManager.fetch(H2PersistenceManager.java:437)
	at siena.AbstractPersistenceManager.get(AbstractPersistenceManager.java:71)
	at siena.BaseQuery.get(BaseQuery.java:111)
	at play.modules.siena.QueryWrapper.get(QueryWrapper.java:88)
	at com.openseedbox.models.Torrent.getByHash(Torrent.java:41)
	at com.openseedbox.models.UserTorrent.getTorrent(UserTorrent.java:227)
	at com.openseedbox.models.User.lambda$0(User.java:67)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.openseedbox.models.User.getActiveTorrents(User.java:68)
	at controllers.Client.index(Client.java:76)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:536)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:473)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:467)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:436)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:159)
	... 1 more
Caused by: java.lang.IllegalArgumentException: Can not set java.lang.String field com.openseedbox.models.Torrent.name to org.h2.jdbc.JdbcClob
	at siena.Util.setField(Util.java:284)
	... 29 more